class NurseDashboardXpath():
    upcoming_consults_number_xpath = "//div[@id='mobile_menu']/ul/li[2]/div[2]/div/ul/li[1]/a[1]/span[2]"
    missed_consults_number_xpath  =  "//div[@id='mobile_menu']/ul/li[2]/div[2]/div/ul/li[2]/a[1]/span[2]"
    team_consults_number_xpath =     "//div[@id='mobile_menu']/ul/li[2]/div[2]/div/ul/li[3]/a[1]/span[2]"
    awaiting_approval_number_xpath = "//div[@id='mobile_menu']/ul/li[4]/div[2]/div/ul/li/a/span[2]"
    prescribed_patient_number_xpath  = "//div[@id='mobile_menu']/ul/li[4]/div[2]/div/ul/li[2]/a/span[2]"
    not_prescribed_patient_number_xpath  = "//div[@id='mobile_menu']/ul/li[4]/div[2]/div/ul/li[3]/a/span[2]"
    active_subscribers_number_path = "//div[@id='mobile_menu']/ul/li[4]/div[2]/div/ul/li[4]/a/span[2]"
    lost_customer_number_xpath = "//div[@id='mobile_menu']/ul/li[4]/div[2]/div/ul/li[5]/a/span[2]"
    non_responsive_number_xpath = "//div[@id='mobile_menu']/ul/li[4]/div[2]/div/ul/li[6]/a/span[2]"

    nurse_profile_xpath = "//div[@id='mobile_menu']/ul/li[5]/a"
    nurse_first_name_xpath = '//div[@id="div_id_first_name"]/input'
    nurse_first_name_star = "//div[@id='div_id_first_name']/label/span"
    nurse_last_name_star = "//div[@id='div_id_last_name']/label/span"
    nurse_last_name_xpath = '//div[@id="div_id_last_name"]/input'
    save_changes_button = "//button[@id='updateButton']"
    profile_update_success_xpath = "//div[@role='alert']"
    upcoming_consults_xpath = "//div[@id='mobile_menu']/ul/li[2]/div[2]/div/ul/li[1]/a"
    upcoming_page_title_text = "//div[@class='container py-4']/div/div/h1"
    new_patient_image_xpath = "//table[@id='datatable']/tbody/tr[1]/td[1]/span/img"
    # search_box = "//input[contains(@placeholder,'Search name or email ...')]"
    search_box = "//input[@placeholder='Search name or email ...']"
    read_order_id = "//div[@class='container py-4']/div[3]/table/tbody/tr[1]/th"
    read_patient_name = "//div[@class='container py-4']/div[3]/table/tbody/tr[1]/td[1]/a"
    read_patient_status = "//div[@class='container py-4']/div[3]/table/tbody/tr/td[3]/span[1]"
    read_doctor_name = "//div[@class='container py-4']/div[3]/table/tbody/tr[1]/td[4]"
    read_consultation_time = "//div[@class='container py-4']/div[3]/table/tbody/tr/td[4]"
    read_treatment_data = "//div[@id='page-content']/div[2]/div[5]/div[3]/div/div[1]/p"
    mark_as_missed_btn = "//button[normalize-space()='Mark As Missed']"
    review_application_btn = "//button[@type='submit'][normalize-space()='Review Application'][1]"
    treatment_number_xpath = "//table[@id='datatable']/tbody/tr[1]/td[2]/span"
    read_patient_awaiting_xpath = "//div[@class='container py-4']/table[1]/tbody[1]/tr[1]/td[2]/span[1]"
    consult_patient_xpath = "//div[@id='mobile_menu']/ul[1]/li[4]/div[1]/a[1]/span"
    consultations_xpath = "//div[@id='mobile_menu']/ul[1]/li[2]/div/a[1]/span[1]"
    patient_approval_letter_xpath = "//div[@class='container py-4']/div[3]/table/tbody/tr[1]/td[3]/span[5]/a"

