class ProfileXpath():
    password = "Password"
    password_xpath = "//div[@class='container py-4']/form/div[1]/ul/li[2]/a"
    # password_xpath = "//span[contains(text(),'Password')]"
    old_password = "//input[@id='id_old_password']"
    new_password = "//input[@id='id_new_password1']"
    new_password_confirm = "//input[@id='id_new_password2']"
    update_btn = "//button[@id='updatePasswordBtn']"
    password_req1 = "//ul[@id='passwordErrors']/li[1]"
    password_req2 = "//p[@id='error_2_id_new_password2']"
    password_req3 = "//p[@id='error_3_id_new_password2']"
    password_req4 = "//p[@id='error_4_id_new_password2']"
    password_req5 = "//p[@id='error_5_id_new_password2']"
    password_updated_success_txt = "//div[@role='alert']"
    medicare_value = "(//div[@class='col-sm-9 text-secondary'])[6]"
    reference_value = "(//div[@class='col-sm-9 text-secondary'])[8]"

    first_name="first_name"
    last_name="last_name"
    consultation_link = "Consultation"
    profile_link = ""
    po_box = "//input[@id='id_parcel_locker_address']"
    address_xpath = "//input[@id='id_mailing_address_placeholder']"
    success_msg_xpath = "//div[@role='alert']"
    phone_number_xpath ="//input[@id='id_phone']"
    first_name_xpath = "//input[@id='id_first_name']"
    last_name_xpath = "//input[@id='id_last_name']"
    dob_xpath = "//input[@id='id_dob']"
    gender_xpath = "//select[@id='id_gender']"
    empty_mailing_address_xpath = "//span[@id='error_1_id_mailing_address_placeholder']/strong"
    phone = "//input[@id='id_phone']"
    mail_addr = "//input[@id='id_mailing_address_placeholder']"
    mail_addr_list = "(//div//span[text()='Trades Hall Place'])[1]"
    update_prof_btn = "//button[@id='updateButton']"
