class SideNavXpath:
    consultations = "//a[@href='/patient/book-consultation/']"
    missed_consults = "//a[@href='/doctor/missed-consultations/']"
    support = "(//a[@href='/patient/support/'])[2]"
    online_store = "//a[@id='onlineStorenew']"

    # profile_link = "Profile"
    profile_link = "//div[@id='mobile_menu']/ul/li[2]/a/span"
    first_name="first_name"
    last_name="last_name"
    consultation_link = "Consultation"
    documents_link = "Documents"
    refer_a_friend_link ="Refer a friend"
    support_link = "Support"
    home_page = "//a[@href='/patient/dashboard/']"