class PatientDashboardXpath():
    next_btn = "(//button[@id='nextButton'])[1]"
    previous_btn = "(//button[@id='previousButton'])[1]"
    get_started_btn = "(//button[@id='getstartedButton'])[1]"
    cancel_verify = "//div[@class='alert-upcoming-text'][normalize-space()='Your appointment is currently under review for approval.']"
    consultation_cancel_verify = "//h5[contains(text(),'Your appointment is currently under review for app')]"
    tooltip_icon = "//div[@id='welcome-btn']"
    # shop_vaporisers = "//div[@class='treatement-card--btn-wrap']//a[@class='btn btn-submit btn-dark'][normalize-space()='Shop vaporiser']"
    # shop_accessoriess = "//div[@class='treatement-card--btn-wrap']//a[@class='btn btn-submit btn-dark'][normalize-space()='Shop accessories']"

    shop_vaporiser = "(//a[@class='btn btn-submit btn-dark'][normalize-space()='Shop vaporiser'])"
    shop_accessories = "(//a[@class='btn btn-submit btn-dark'][normalize-space()='Shop accessories'])"
    modal_close_btn = "//button[@id='close']"
    online_store_modal = "//div[@id='onlineStoreModal']//div[@class='modal-body']"
    onboard_tooltip_modal = "(//div[@class='onboardModal-wrapper'])[1]"
