class PatientNoteXpath():
    medicare_number = "//input[@id='id_medicare_number']"
    expiry_date = "//input[@id='id_medicare_expiry_date']"
    reference_number = "//input[@id='id_medicare_reference_number']"
    ihi_number = "//input[@name='ihi_number']"
    occupation = "//input[@name='occupation']"
    weight = "//input[@name='weight']"
    height = "//input[@name='height']"
    smoker = "//input[@name='tobacco']"
    drinker = "//input[@name='alcohol']"
    patient_symptom_select = "//select[@name='severity_of_symptoms']"
    allergies = "//input[@name='allergiesdetails']"
    sleep = "//input[@name='sleep']"
    therapies = "//input[@name='alternativetherapies']"
    year_of_diagnosed = "//input[@name='yeardiagnosed']"
    previous_practitioner = "//input[@name='previousdoctor']"
    medications = "//textarea[@name='currentmedicines']"
    symptoms = "//textarea[@name='symptoms']"
    chronic_pain = "//textarea[@id='id_symptoms_of_chronic_pain']"
    medical_condition = "//textarea[@id='id_medical_cond_being_treated_mc']"
    dva_funding_1 = "(//div[@class='form-check form-check-inline'])[1]"
    dva_funding_2 = "(//div[@class='form-check form-check-inline'])[2]"
    attempted_treatments = "//textarea[@id='id_list_attempted_treatments']"
    reapplication_check_1 = "(//div[@class='form-check form-check-inline'])[3]"
    reapplication_check_2 = "(//div[@class='form-check form-check-inline'])[4]"
    reapplication_check_3 = "(//div[@class='form-check form-check-inline'])[5]"
    reapplication_check_4 = "(//div[@class='form-check form-check-inline'])[6]"
    reapplication_reason = "//input[@id='id_reasons_for_reapplication_other']"
    therapy_outcomes = "//textarea[@id='id_report_outcomes_therapy']"
    mental_health_monitoring = "//textarea[@id='id_report_monitoring_mental_health_issues']"
    scroll_to_update_btn = "//h3[normalize-space()='Patient Note']"
    update_btn = "//button[contains(text(), 'Update')]"
    save_btn = "//input[@id='submit-id-']"
    update_treatment_plan_btn = "//button[@id='ChangePrescriptionBtn']"
    next_btn = "//button[normalize-space()='Next']"
