class DropdownNavigationXpath():
    naviagtion_drpdwn = "//div[@role='button']"
    drpdwn_name = "//ul[@class='dropdown-menu dropdown-menu-lg-end show']//div[@class='profile-id']"
    profile_menu = "//a[contains(text(),'Profile')]"
    password_menu = "//a[contains(text(),'Password')]"
    logout = "//a[contains(text(),'Logout')]"
    naviagtion_drpdwn_menus = "//ul[@class='dropdown-menu dropdown-menu-lg-end show']"
    verify_profile = "//a[normalize-space()='Edit']"
    verify_password = "//a[normalize-space()='Change Password']"
    verify_logout = "//h3[normalize-space()='Log In Account']"
