class TreatmentPlanXpath:
    select_treatment_plan_btn = "//button[@id='CreateSkipTGAPrescriptionBtn']"
    modify_quantity_btn = "//button[@id='modify-quantity-btn']"
    start_treatment_plan_btn = "//button[normalize-space()='Start Treatment Plan']"
    confirm_btn = "//button[normalize-space()='CONFIRM']"
    select_balance_oil = "//select[@id='id_Balance-Oil---30ml']"
    select_cbd_oil = "//select[@id='id_CBD-Oil']"
    select_hybrid_vape_cart = "//select[@id='id_Hybrid-5050-Vape-Cart']"
    select_hybrid_flower = "//select[@id='id_Hybrid-Flower']"
    select_indica_vape_cat = "//select[@id='id_Indica-Vape-Cartridge']"
    select_indica_flower = "//select[@id='id_Indica-Flower']"
    select_sativa_flower = "//select[@id='id_Sativa-Flower']"
    select_sativa_vape_cat = "//select[@id='id_Sativa-Vape-Cartridge']"
    next_btn = "//button[@id='prescription-submit-btn']"
    update_btn = "//button[normalize-space()='Update']"
    approve_btn = "//input[@id='submit-id-submit']"

    veteran_balance_oil_1010 = "//select[@id='id_Balance-Oil---30ml---Veteran']"
    veteran_balance_oil_2525 = "//select[@id='id_Balance-Oil-2525-30mgml-Veteran']"
    veteran_hybrid_flower = "//select[@id='id_Balanced-Hybrid-Flower10g-Veteran']"
    veteran_indica_flower_thc ="//select[@id='id_Indica-Flower-Veteran']"
    veteran_pure_isolate_cbd_100 = "//select[@id='id_Pure-Isolate-CBD100-oil100mgml-CBD-Veteran']"
    veteran_pure_isolate_cbd_220 = "//select[@id='id_Pure-Isolate-CBD220-oil220-mgmL-CBD-Veteran']"
    veteran_sativa_flower_thc = "//select[@id='id_Sativa-Flower-Veteran']"
    veteran_thc_oil = "//select[@id='id_THC-Oil30mL-Veteran']"
    veteran_full_spectrum_cbd_100 = "//select[@id='id_CBD-Oil-Veteran']"


