class SearchConsultsXpath():
    SearchBTN = "//span[text()='Search']"
    search_box = "//input[@name='search']"
    review_application_btn = "//button[@type='submit'][normalize-space()='Review Application'][1]"
    view_pending_prescription = "//tr[1]/td[5]/a[normalize-space()='View Pending Prescription']"
    mark_as_missed_btn = "//button[normalize-space()='Mark As Missed']"

    patient_summary_text = "//h1[contains(text(),'Patient Summary')]"
    read_upcoming_consults_number = "//a[contains(@href,'/doctor/upcoming-consults')]/span[2]"
    read_missed_consults_number = "//a[contains(@href,'/doctor/missed-consultations')]/span[2]"
    missed_patient_name =  "//table[@id='datatable']/tbody/tr/td/a"
    missed_patient_status = "//table[@id='datatable']/tbody/tr/td[3]/span[1]"
    read_order_id = "//div[@class='container py-4']/div[3]/table/tbody/tr[1]/th"
    read_patient_name = "//div[@class='container py-4']/div[3]/table/tbody/tr[1]/td[1]/a"
    read_patient_status = "//div[@class='container py-4']/div[3]/table/tbody/tr/td[3]/span[1]"
    read_doctor_name = "//div[@class='container py-4']/div[3]/table/tbody/tr[1]/td[4]"
    read_consultation_time = "//div[@class='container py-4']/div[3]/table/tbody/tr/td[4]"
    read_treatment_data = "//div[@id='page-content']/div[2]/div[5]/div[3]/div/div[1]/p"

    view_profile = "//tbody/tr[1]/td[1]/a[1]"
    naviagtion_drpdwn = "//div[@role='button']"